Gnome45
RaphaelRochet/arch-update pull request #218
Opened 2023-09-05 13:12 UTC by gilvbp

Partially working, //TODO need to fix some features 

![image](https://github.com/RaphaelRochet/arch-update/assets/2273754/b5c2deb4-cf98-42a9-92ff-65f74ebd19b8)

2023-09-05 13:36 UTC, RaphaelRochet requested changes
Thanks for the effort, much appreciated.
But when you change every bit of space in code to your liking, if create so much mess in the diff that's not readable.  Please respect the current code spacing. And do not change anything that's not related to the PR.

2023-09-05 13:38 UTC, RaphaelRochet commented
That's going to be interesting ...

2023-09-05 14:28 UTC, gilvbp commented on .eslintrc.yml
sorry, I will remove

2023-09-05 14:38 UTC, gilvbp commented on prefs.js
> +        settings.bind('package-info-cmd', buildable.get_object('field_packageinfocmd'), 'text', Gio.SettingsBindFlags.DEFAULT);
> Oh, you didn't like my spacings ? What a mess. I get the `Me` to `this` change though.

My mistake. I'll rollback the code format. That was intellij

2023-09-05 14:42 UTC, gilvbp commented on metadata.json
> +  "settings-schema": "org.gnome.shell.extensions.arch-update",
Yes, i just remember to eliminate the initTranslation method. Check this: https://gjs.guide/extensions/upgrading/gnome-shell-45.html#extensionutils
Just fix with this commit: https://github.com/gilvbp/arch-update/commit/b1d144c242ec4ab4870f65892b3766317d6fffe6

2023-09-08 18:56 UTC, gilvbp reviewed
Review finished

2023-09-08 20:13 UTC, RaphaelRochet requested changes
With all your unrelated changes (spacing, templates, empty lines, refactoring) you make it very very hard to review changes.
Please review all your changes so that there is only changes strictly required and related to the PR.
Also please respect existing code style : spacings, empty lines, strings ...

2023-09-08 20:13 UTC, RaphaelRochet commented on extension.js
> +                        });
Don't change existing code without good reason, and related to PR

2023-09-08 20:13 UTC, RaphaelRochet commented on extension.js
> +                        }).length);
Don't change existing code without good reason, and related to PR

2023-09-08 20:13 UTC, RaphaelRochet commented on extension.js
> +                            updateList.push(out);
Don't change existing code without good reason, and related to PR

2023-09-08 20:13 UTC, RaphaelRochet commented on extension.js
> +                        return;
Don't change existing code without good reason, and related to PR

2023-09-08 20:13 UTC, RaphaelRochet commented on extension.js
> +                    Util.spawnCommandLine(`kill ${this._updateProcess_pid}`);
Don't change existing code without good reason, and related to PR

2023-09-08 20:13 UTC, RaphaelRochet commented on extension.js
> +                            let gicon = Gio.icon_new_for_string(`${archUpdateIndicatorExtension.dir.get_child('icons').get_path()}/arch-updates-logo.svg`);
Don't change existing code without good reason, and related to PR
I get the change from Me to archUpdateIndicatorExtension though.

2023-09-08 20:13 UTC, RaphaelRochet commented on extension.js
> +                        });
Don't change existing code without good reason, and related to PR

2023-09-08 20:13 UTC, RaphaelRochet commented on extension.js
> +    }
What is that ?

2023-09-08 20:22 UTC, RaphaelRochet commented
Also can you tell what is missing ?
I may end up creating a new branch, if this is not fully functional.

2023-09-08 21:30 UTC, closed without merging

2023-09-08 21:41 UTC, gilvbp commented
> Also can you tell what is missing ? I may end up creating a new branch, if this is not fully functional

It's better to create a new branch code (ex gnome-45), and I will rollback some code, eslintrct and IntelliJ formated the code that messed up. Need to rollback. Prefs.js and Update list button need to get working.